In [1]:
import torch
import numpy as np



直接生成张量

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

通过Numpy数组来生成张量

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_data

tensor([[1, 2],
        [3, 4]])

通过已有的张量来生成新的张量
新的张量将继承已有张量的数据属性(结构、类型), 也可以重新指定新的数据类型。

In [4]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: \n{x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float32)
print(f"x_rand tensor: \n{x_rand} \n")

ones tensor: 
tensor([[1, 1],
        [1, 1]]) 

x_rand tensor: 
tensor([[0.0701, 0.3303],
        [0.4778, 0.8198]]) 



通过指定数据维度来生成张量

In [5]:
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor =  torch.zeros(shape)

print(f"random tensor:\n {rand_tensor}\n")
print(f"ones tensor:\n {ones_tensor}\n")
print(f"zeros tensor:\n {zeros_tensor}\n")

random tensor:
 tensor([[0.5297, 0.2207, 0.4695],
        [0.3164, 0.0594, 0.0994]])

ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



张量属性

In [6]:
tensor = torch.rand(3,4)
print(f"tensor data: {tensor}")
print(f"tensor shape: {tensor.shape}")
print(f"dtype : {tensor.dtype}")
print(f"device tensor in stored on:{tensor.device}")

tensor data: tensor([[0.9235, 0.3224, 0.4875, 0.1161],
        [0.2045, 0.4898, 0.1466, 0.8452],
        [0.5143, 0.6199, 0.1340, 0.6412]])
tensor shape: torch.Size([3, 4])
dtype : torch.float32
device tensor in stored on:cpu


张量运算
判断是否可以在GPU上执行

In [17]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(tensor)


tensor([[1, 2, 3],
        [4, 5, 6]])


张量的索引和切片

In [8]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0  # 将第1列(从0开始)的数据全部赋值为0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


张量的拼接

In [9]:
t1 = torch.cat([tensor,tensor,tensor])
print(tensor.shape)
print(t1.shape)
print(t1)


torch.Size([4, 4])
torch.Size([12, 4])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


函数stack()对序列数据内部的张量进行扩维拼接，指定维度由程序员选择、大小是生成后数据的维度区间。

In [10]:
T1 = torch.tensor([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
# 假设是时间步T2
T2 = torch.tensor([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(T1.shape)
print(T2.shape)

print(torch.stack((T1,T2),dim=0).shape)
print(torch.stack((T1,T2),dim=0))


print(torch.stack((T1,T2),dim=1).shape)
print(torch.stack((T1,T2),dim=1))

print(torch.stack((T1,T2),dim=2).shape)
print(torch.stack((T1,T2),dim=2))


torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([2, 3, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])
torch.Size([3, 2, 3])
tensor([[[ 1,  2,  3],
         [10, 20, 30]],

        [[ 4,  5,  6],
         [40, 50, 60]],

        [[ 7,  8,  9],
         [70, 80, 90]]])
torch.Size([3, 3, 2])
tensor([[[ 1, 10],
         [ 2, 20],
         [ 3, 30]],

        [[ 4, 40],
         [ 5, 50],
         [ 6, 60]],

        [[ 7, 70],
         [ 8, 80],
         [ 9, 90]]])


张量的乘积和矩阵乘法

In [11]:
import copy
tensor = torch.tensor([[1,2,3],[4,5,6]])

print(tensor)
tensor_1 = copy.deepcopy(tensor)
tensor_2 = copy.deepcopy(tensor)
#逐个元素相乘结果
print(f"tensor.mul(tensor):\n{tensor_1.mul(tensor_2)}\n")
# 等价写法:
print(f"tensor * tensor: \n {tensor_1 * tensor_2}")

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor.mul(tensor):
tensor([[ 1,  4,  9],
        [16, 25, 36]])

tensor * tensor: 
 tensor([[ 1,  4,  9],
        [16, 25, 36]])


下面写法表示张量与张量的矩阵乘法:

In [12]:

print(f"tensor.matmul(tensor.T): \n {tensor_1.matmul(tensor_1.T)} \n")
# 等价写法:
print(f"tensor @ tensor.T: \n {tensor_1 @ tensor_1.T}")


tensor.matmul(tensor.T): 
 tensor([[14, 32],
        [32, 77]]) 

tensor @ tensor.T: 
 tensor([[14, 32],
        [32, 77]])


 自动赋值运算
 自动赋值运算通常在方法后有 _ 作为后缀, 例如: x.copy_(y), x.t_()操作会改变 x 的取值。
 自动赋值运算虽然可以节省内存, 但在求导时会因为丢失了中间过程而导致一些问题, 所以我们并不鼓励使用它

In [13]:
print(tensor_1)

print(tensor_1.add_(4))
print(tensor_1)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 5,  6,  7],
        [ 8,  9, 10]])
tensor([[ 5,  6,  7],
        [ 8,  9, 10]])


Tensor与Numpy的转化

In [14]:
t = torch.ones(5)
print(f"r:{t}")
n= t.numpy()
print(f"n:{n}")
# 修改张量的值，则Numpy array数组值也会随之改变。
t.add_(2)
print(f"n:{n}")

r:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]
n:[3. 3. 3. 3. 3.]


由Numpy array数组转为张量

In [16]:
n = np.ones([5,3])
t= torch.from_numpy(n)
print(f"t:{t}")
np.add(n, 2, out=n)
print(f"t:{t}")

t:tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
t:tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)
